// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_doImgproc (
hls::stream<struct ap_axiu<8, 2, 5, 6 > > (&inStream),
hls::stream<struct ap_axis<8, 2, 5, 6 > > (&outStream),
char kernel[9]);
